OdeToFood/OdeToFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OdeToFood/OdeToFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OdeToFood/OdeToFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OdeToFood/OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood
{
    public class ClientRestaurantsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

OdeToFood/OdeToFood/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        public Restaurant Restaurant { get; set; }

        public DeleteModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int id)
        {
            Restaurant = restaurantData.GetById(id);

            if (Restaurant == null)
                return RedirectToPage("./NotFound");

            return Page();
        }

        public IActionResult OnPost(int id)
        {
            var restaurant = restaurantData.Delete(id);

            if (restaurant == 0)
                return RedirectToPage("./NotFound");

            TempData["Message"] = "Restaurant deleted";
            return RedirectToPage("./List");
        }
    }
}

OdeToFood/OdeToFood/Pages/Restaurants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood
{
    public class DetailModel : PageModel
    {
        public Restaurant Restaurant { get; set; }

        public IRestaurantData RestaurantData { get; }

        [TempData]
        public string Message { get; set; }

        public DetailModel(IRestaurantData restaurantData)
        {
            RestaurantData = restaurantData;
        }

        public IActionResult OnGet(int id)
        {
            Restaurant = RestaurantData.GetById(id);

            if (Restaurant == null)
                return RedirectToPage("./NotFound");

            return Page();
        }
    }
}

OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData RestaurantData;
        private readonly IHtmlHelper htmlHelper;

        [BindProperty] //only with post op
        public Restaurant Restaurant { get; set; }

        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public EditModel(IRestaurantData restaurantData, IHtmlHelper htmlHelper)
        {
            this.RestaurantData = restaurantData;
            this.htmlHelper = htmlHelper;
        }

        public IActionResult OnGet(int? id)
        {
            if (id != null)
            {
                Restaurant = RestaurantData.GetById(id.Value);

                if (Restaurant == null)
                    return RedirectToPage("./NotFound");
            }
            else
            {
                Restaurant = new Restaurant
                {
                    Cuisine = CuisineType.None
                };
            }

            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();
            }

            if (Restaurant.RestaurantId == 0)
                RestaurantData.Add(Restaurant);
            else
                RestaurantData.Update(Restaurant);

            RestaurantData.Commit();

            TempData["Message"] = "Restaurant saved!";
            //only shows on the next request

            return RedirectToPage("./Detail", new { id = Restaurant.RestaurantId });
        }
    }
}

OdeToFood/OdeToFood/Pages/Restaurants/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using OdeToFood.Core;
using OdeToFood.Data;
using System.Collections.Generic;

namespace OdeToFood
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly ILogger<ListModel> logger;

        public string Message { get; set; }

        public IRestaurantData RestaurantData { get; }

        public IEnumerable<Restaurant> Restaurants { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public ListModel(IConfiguration config, IRestaurantData restaurantData, ILogger<ListModel> logger)
        {
            this.config = config;
            RestaurantData = restaurantData;
            this.logger = logger;
        }

        public void OnGet()
        {
            logger.LogError("log");
            Message = config["Message"];
            Restaurants = RestaurantData.GetRestaurantsByName(SearchTerm);
        }
    }
}

OdeToFood/OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class RestaurantCountViewComponent : ViewComponent
    {
        private readonly IRestaurantData restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IViewComponentResult Invoke()
        {
            var count = restaurantData.GetCountOfRestaurants();
            return View("", count);
        }
    }
}

OdeToFood/OdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OdeToFood/OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml
@page
@model OdeToFood.ClientRestaurantsModel
@{
    ViewData["Title"] = "ClientRestaurants";
}

<h1>Client Restaurants</h1>

<table id="restaurants" class="table"></table>

@section Scripts {
    <environment include="Development">
        <script src="~/node_modules/datatables.net/js/jquery.dataTables.js"></script>
        <script src="~/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js"></script>

        <link href="~/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.js"></script>
    </environment>

    <script>
        $(function () {
            var cuisines = ["Unknown", "Mexican", "Italian", "Indian"];

            $.ajax("/api/restaurants/",
                { method: "GET" })
                .then(function (response) {
                    $("#restaurants").dataTable({
                        data: response,
                        columns: [
                            { "data": "name" },
                            { "data": "location" },
                            { "data": "cuisine", "render": function (data) { return cuisines[data]; } }
                        ]
                    });
                });
        });
    </script>
}

OdeToFood/OdeToFood/Pages/Restaurants/Delete.cshtml
@page "{id}"
@model OdeToFood.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete!</h2>

<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurant.Name?
</div>

<form method="post">

    <button type="submit" name="delete" class="btn btn-danger" value="">
        Yes
    </button>

    <a asp-page="List" class="btn btn-primary">Cancel</a>
</form>

OdeToFood/OdeToFood/Pages/Restaurants/Detail.cshtml
@page "{id:int}"

@model OdeToFood.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h1>@Model.Restaurant.Name</h1>
<div>
    Id: @Model.Restaurant.RestaurantId
</div>
<div>
    Location: @Model.Restaurant.Location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>

@if (Model.Message != null)
{
    <div class="alert alert-info mt-3">@Model.Message</div>
}

<a asp-page="./List" class="btn btn-outline-secondary">All Restaurants</a>

OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{id:int?}"
@model OdeToFood.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Editing @Model.Restaurant.Name</h2>

<form method="post">

    <input type="hidden" asp-for="Restaurant.RestaurantId" /> @*asp-for => seta o name e o value*@

    <div class="form-group">
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Restaurant.Location"></label>
        <input asp-for="Restaurant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Location"></span>
    </div>

    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select class="form-control" asp-for="Restaurant.Cuisine" asp-items="Model.Cuisines"></select>
        <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>
    </div>

    <button type="submit" class="btn btn-outline-success">
        Save
    </button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OdeToFood/OdeToFood/Pages/Restaurants/List.cshtml
@page
@model OdeToFood.ListModel
@{
    ViewData["Title"] = "Restaurants";
}

<h1>Restaurants</h1>

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control"
                   asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-secondary">
                    <span class="fa fa-search"></span>
                </button>
            </span>
        </div>
    </div>
</form>

@foreach (var restaurant in Model.Restaurants)
{
    <partial name="_Summary" model="restaurant" />
}

<a asp-page="./Edit" class="btn btn-primary mb-4 mt-4">New</a>

<div>@Model.Message</div>

OdeToFood/OdeToFood/Pages/Restaurants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h2>Your Restaurant was not found</h2>

<a asp-page="./List" class="btn btn-outline-primary">All Restaurants</a>

OdeToFood/OdeToFood/Pages/Restaurants/_Summary.cshtml
@using OdeToFood.Core

@model Restaurant

<div class="card">
    <div class="card-header">
        <h3>@Model.Name</h3>
    </div>
    <div class="card-body">
        <span>Location: @Model.Location</span>
        <span>Cuisine: @Model.Cuisine</span>
    </div>
    <div class="card-footer">
        <a class="btn bt-lg"
           asp-page="./Detail" asp-route-id="@Model.RestaurantId">
            <i class="fa fa-search-plus"></i>
        </a>
        <a class="btn bt-lg"
           asp-page="./Edit" asp-route-id="@Model.RestaurantId">
            <i class="fa fa-pencil-alt"></i>
        </a>
        <a class="btn bt-lg"
           asp-page="./Delete" asp-route-id="@Model.RestaurantId">
            <i class="fa fa-trash"></i>
        </a>
    </div>
</div>

OdeToFood/OdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="well">
    There are @Model restaurants here. <a asp-page="/Restaurants/List">See them all!</a>
</div>

OdeToFood/OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- CSS -->
    <environment include="Development">
        <script src="~/lib/fontawesome-free-5.12.0-web/css/all.css"></script>
    </environment>

    <!-- JS -->
    <environment include="Development">
        <script src="~/lib/fontawesome-free-5.12.0-web/js/all.js"></script>
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Home" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Restaurants" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Privacy" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <vc:restaurant-count></vc:restaurant-count>
            &copy; @DateTime.Now.Year - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>